test:
	# curl -H "Host: https-example.foo.com" https://180.93.181.81/webserver -k

	# go clean -testcache && go test -v ./k8s.go ./test_vlb.go ./utils.go ./thefirst_test.go
	# go clean -testcache && go test -v ./k8s.go ./test_vlb.go ./utils.go ./thesecond_test.go
	go clean -testcache && go test -v ./k8s.go ./test_vlb.go ./utils.go ./thethird_test.go