name: golangci-lint
on:
  push:
    branches:
      - dev
      - main

jobs:
  golangci:
    name: lint-codebase
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: "1.20"
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.52.2
          args: --timeout 15m0s --verbose --out-${NO_FUTURE}format tab
