name: Lint plugin readmes
on:
  push:
    branches:
      - dev
      - main

jobs:
  run-readme-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: "1.21.8"
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v42
        with:
          base_sha: ${{ github.event.pull_request.base.sha }}
          files: ./plugins/**/README.md
      - name: Run readme linter on changed files
        if: steps.changed-files.outputs.any_changed == 'true'
        run: go run ./tools/readme_linter ${{ steps.changed-files.outputs.all_changed_files }}
